=== eonalion/JavaWebCourse/5_XML_XSD/data/greenhouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/greenhouse"
           xmlns="http://www.example.com/greenhouse">

    <xs:element name="flower" type="flowerType" abstract="true"/>
    <xs:element name="outdoor-flower" type="outdoorFlowerType" substitutionGroup="flower"/>
    <xs:element name="indoor-flower" type="indoorFlowerType" substitutionGroup="flower"/>

    <xs:element name="flowers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="flower" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="flowerType">
        <xs:sequence>
            <xs:element type="soilType" name="soil"/>
            <xs:element type="xs:string" name="origin"/>
            <xs:element type="visualParametersType" name="visual-parameters"/>
            <xs:element type="growingTipsType" name="growing-tips"/>
            <xs:element type="multiplyingType" name="multiplying"/>
        </xs:sequence>
        <xs:attribute name="name" type="nameType" use="required"/>
    </xs:complexType>

    <xs:complexType name="outdoorFlowerType">
        <xs:complexContent>
            <xs:extension base="flowerType">
                <xs:sequence>
                    <xs:element type="lifetimeType" name="lifetime"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="lifetimeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="annual"/>
            <xs:enumeration value="biennial"/>
            <xs:enumeration value="perennial"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="indoorFlowerType">
        <xs:complexContent>
            <xs:extension base="flowerType">
                <xs:sequence>
                    <xs:element type="xs:boolean" name="flowering"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(.){1,100}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="soilType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="podzolic"/>
            <xs:enumeration value="sod-podzolic"/>
            <xs:enumeration value="loam"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="visualParametersType">
        <xs:sequence>
            <xs:element type="xs:string" name="stem-color"/>
            <xs:element type="xs:string" name="leaf-color"/>
            <xs:element type="xs:positiveInteger" name="size"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="growingTipsType">
        <xs:sequence>
            <xs:element type="temperatureType" name="temperature"/>
            <xs:element type="xs:positiveInteger" name="water"/>
        </xs:sequence>
        <xs:attribute name="heliphilous" type="xs:boolean" use="optional" default="true"/>
    </xs:complexType>

    <xs:simpleType name="temperatureType">
        <xs:restriction base="xs:short">
            <xs:minInclusive value="-40"/>
            <xs:maxInclusive value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="multiplyingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="leaves"/>
            <xs:enumeration value="cuttings"/>
            <xs:enumeration value="seeds"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== eonalion/JavaWebCourse/5_XML_XSD/data/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns="http://www.example.com/greenhouse"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.com/greenhouse greenhouse.xsd">

    <indoor-flower name="Indoor flower 1">
        <soil>loam</soil>
        <origin>Origin1</origin>
        <visual-parameters>
            <stem-color>color1</stem-color>
            <leaf-color>color2</leaf-color>
            <size>230</size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <water>500</water>
        </growing-tips>
        <multiplying>seeds</multiplying>
        <flowering>true</flowering>
    </indoor-flower>

    <indoor-flower name="Indoor flower 2">
        <soil>sod-podzolic</soil>
        <origin>Origin2</origin>
        <visual-parameters>
            <stem-color>color1</stem-color>
            <leaf-color>color2</leaf-color>
            <size>200</size>
        </visual-parameters>
        <growing-tips heliphilous="true">
            <temperature>15</temperature>
            <water>200</water>
        </growing-tips>
        <multiplying>leaves</multiplying>
        <flowering>false</flowering>
    </indoor-flower>

    <outdoor-flower name="Outdoor flower 1">
        <soil>podzolic</soil>
        <origin>Origin1</origin>
        <visual-parameters>
            <stem-color>color1</stem-color>
            <leaf-color>color2</leaf-color>
            <size>500</size>
        </visual-parameters>
        <growing-tips heliphilous="false">
            <temperature>15</temperature>
            <water>500</water>
        </growing-tips>
        <multiplying>cuttings</multiplying>
        <lifetime>perennial</lifetime>
    </outdoor-flower>

</flowers>

=== eonalion/JavaWebCourse/5_XML_XSD/data/greenhouse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns="http://www.example.com/greenhouse"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.com/greenhouse greenhouse.xsd">
    <flower name="Name">
        <soil>loam</soil>
        <origin>Origin</origin>
        <visual-parameters>
            <stem-color>color1</stem-color>
            <leaf-color>color2</leaf-color>
            <size>100</size>
        </visual-parameters>
        <growing-tips heliphilous="true">
            <temperature>15</temperature>
            <water>500</water>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>
</flowers>
